version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@1.3.0

workflows:
  version: 2.1
  generate-config:
    jobs:
      - path-filtering/filter:
          filters:
            tags:
              only:
                - /.*/
          base-revision: main
          config-path: .circleci/continue_config.yml
          mapping: |
            .circleci/.* run-all-workflows true
            ProjectLLM-backend/.* run-all-workflows true
            ProjectLLM-bindings/python/.* run-python-workflow true
            ProjectLLM-bindings/typescript/.* run-ts-workflow true
            ProjectLLM-chat/.* run-chat-workflow true
